# numpy

In [2]:
import numpy as  np

In [12]:
# using python list
lst = [1,2,3,4,5,6,7,8,9]
print(type(lst))

arr1d = np.array(lst)
print(type(arr1d))
print(arr1d)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [14]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
arr1d * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr1d - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [20]:
arr1d + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
arr1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [28]:
arr1d / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
arr1d.size

9

In [32]:
arr1d.ndim

1

In [34]:
arr1d.shape

(9,)

In [46]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
lst2d = [[1,2,3], [11,22,33],[111,222,333]]
lst2d

[[1, 2, 3], [11, 22, 33], [111, 222, 333]]

In [62]:
arr2d = np.array(lst2d)
print(arr2d)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [60]:
arr2d.ndim

2

In [84]:
arr2d = np.arange(36).reshape(4,9)
print(arr2d)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [94]:
print(arr1d)
arr1d[7]

[0 1 2 3 4 5 6 7 8 9]


7

In [88]:
arr1d[5]

5

In [90]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [110]:
arr2d[-1][-1]

35

In [108]:
arr1d[4:8]

array([4, 5, 6, 7])

In [126]:
arr2d[3:4]

array([[27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [128]:
arr2d[1:2,2:7]

array([[11, 12, 13, 14, 15]])

In [164]:

arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [178]:
arr2d[1:,1]

array([10, 19, 28])