# arange in numpy

## np.arange([start], stop, [step], dtype=None)


In [3]:
import numpy as np

In [7]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Create an array from 5 to 15 with a step of 2
arr2 = np.arange(5, 15, 2) 
print(arr2)

[ 5  7  9 11 13]


In [21]:
arr3 = np.arange(3,20,4)
print(arr3)

[ 3  7 11 15 19]


In [23]:
arr4 = np.array([3, 1, 2]

SyntaxError: incomplete input (4285772355.py, line 1)